spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homework34
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    ua.hillel.homeworks.homework36: INFO
    org.springframework.web: INFO
  file:
    path: log/